# Generated by Django 4.1.6 on 2023-05-01 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Посты'},
        ),
    ]
