# Generated by Django 4.1.6 on 2023-05-26 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_alter_post_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Pet',
        ),
    ]
