# Generated by Django 4.1.6 on 2023-05-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_rename_post_pet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'verbose_name': 'Животные'},
        ),
        migrations.AlterField(
            model_name='pet',
            name='data',
            field=models.DateField(verbose_name='День рождение питомца'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(upload_to='pets/images', verbose_name='Изображение животного'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='title',
            field=models.CharField(max_length=40, verbose_name='Кличка'),
        ),
    ]
